story5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webs5.urls')),
]

webs5/urls.py
from django.urls import path

from . import views
from .views import Story5_matkul, Story5_tambahMatkul, Story5_detailMatkul, hapus_matkul

app_name = 'webs5'

urlpatterns = [
    path('', views.Story1, name='Story1'),
    path('Story3_aboutme', views.Story3_aboutme, name='aboutme'),
    path('Story3_contact', views.Story3_contact, name='contact'),
    path('Story3_eduskill', views.Story3_eduskill, name='eduskill'),
    path('home', views.home, name='home'),
    path('Story5_matkul', views.Story5_matkul, name='s5matkul'),
    path('Story5_tambahMatkul', views.Story5_tambahMatkul, name='s5tm'),
    path('matkul/<int:id>', views.Story5_detailMatkul, name='s5dm'),
    path('hapus_matkul/<int:id>', views.hapus_matkul, name='delete'),
]

webs5/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
pilihan_semester = [
    ("2019/2020 Gasal","2019/2020 Gasal"),
    ("2019/2020 Genap","2019/2020 Genap"),
    ("2020/2021 Gasal","2020/2021 Gasal"),
    ("2020/2021 Genap","2020/2021 Genap"),
    ("2021/2022 Gasal","2021/2022 Gasal"),
    ("2021/2022 Genap","2021/2022 Genap"),
    ("2022/2023 Gasal","2022/2023 Gasal"),
    ("2022/2023 Genap","2022/2023 Genap")
]

class Matkul(models.Model):
    nama_matkul = models.TextField(max_length = 50)
    nama_dsn = models.TextField(max_length = 50)
    sks = models.IntegerField()
    deskripsi = models.TextField(max_length = 300)
    semester = models.TextField(choices = pilihan_semester)
    ruangan = models.TextField(max_length = 40)

    def __str__(self):
        return "{} ({})".format(self.nama_matkul, self.nama_dsn)
    
    def get_absolute_url(self):
        return reverse("webs5:s5dm", args=[self.id])

webs5/forms.py
from django import forms
from .models import Matkul

class MatkulForm(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = "__all__"

webs5/views.py
from django.shortcuts import render, redirect
from .models import Matkul
from .forms import MatkulForm
from django.contrib import messages

# Create your views here.
def Story1(request):
    return render(request, 'Story1.html')

def Story3_aboutme(request):
    return render(request, 'Story3_aboutme.html')

def Story3_contact(request):
    return render(request, 'Story3_contact.html')

def Story3_eduskill(request):
    return render(request, 'Story3_eduskill.html')

def home(request):
    return render(request, 'home.html')

def Story5_matkul(request):
    context = {
        "lessons" : Matkul.objects.all().order_by("-id"),
    }
    return render(request, "Story5_matkul.html", context)

def Story5_tambahMatkul(request):
    if request.method == "POST":
        mForm = MatkulForm(request.POST)
        if mForm.is_valid():
            mForm.save()
            messages.add_message(request, messages.SUCCESS, "Mata kuliah {} telah berhasil ditambahkan!".format(request.POST["nama_matkul"]))
        return redirect("webs5:s5matkul")
    return render(request, "Story5_tambahMatkul.html")

def Story5_detailMatkul(request, id):
    mataKuliah = Matkul.objects.get(id=id)
    context = {
        "matkul" : mataKuliah,
    }
    return render(request, "Story5_detailMatkul.html", context)

def hapus_matkul(request, id):
    if request.method == "POST":
        mkul = Matkul.objects.get(id=id)
        mkul.delete()
        messages.add_message(request, messages.SUCCESS, "Mata kuliah {} telah berhasil dihapus!".format(mkul.nama_matkul))
    return redirect("webs5:s5matkul")

webs5/templates/Story1.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<style>
    html{background-color:rgb(68, 150, 182) ;}
    .Story1{background-color:rgb(68, 150, 182) ;}
</style>
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color:rgb(68, 150, 182)">
    <a class="navbar-brand" href="#">BIODATA</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'webs5:home' %}">Story 3</a>
        <a class="nav-item nav-link" href="{% url 'webs5:s5matkul' %}">Story 5</a>
      </div>
    </div>
</nav>
    <div class="Story1">
        <img src="https://scontent-xsp1-2.xx.fbcdn.net/v/t1.0-9/2023_114083358968846_8137644105767008273_n.jpg?_nc_cat=101&_nc_sid=09cbfe&_nc_eui2=AeHKpKQmiyLaoebc2WaWd1SMOZhs_gaJAwU5mGz-BokDBTJ_7Zznc1vyT7ps7k2GLHBpN7QxvMoS-ZP5IktUOvJN&_nc_ohc=-7IU7ZyDc1gAX-jjRS4&_nc_ht=scontent-xsp1-2.xx&oh=f7be915e5d77daab31cd675b16f003b3&oe=5F9179A1" alt="Foto saya" width="300" height="300">
        <br>
        <h2>Perkenalkan, nama saya Muhammad Daffa Yudhistira Dwipayana</h2>
        <p>NPM : 1906353441</p>
        <p>Umur : 19 tahun</p>
        <p>Angkatan : 2019</p>
        <p>Hobi : Bermain game dan membaca komik</p>
        <p>Tempat kuliah : Universitas Indonesia</p>
        <h3>Deskripsi diri</h3>
        <p>Jika saya harus mendeskripsikan diri saya, saya orangnya itu baik dan ramah terhadap orang lain.<br>
            Sifat buruk saya diantaranya adalah agak pemalas jika mengerjakan sesuatu yang sulit.<br>Namun,
            jika saya menemukan suatu hal yang saya suka dan bisa saya kerjakan,<br> saya akan bersungguh-sungguh 
            dalam mengerjakan hal tersebut.
        </p>   
        <h3>Riwayat Pendidikan</h3>
        <ol>
            <li>SDI PB Soedirman</li>
            <li>SMP Negeri 103 Jakarta</li>
            <li>SMA Negeri 98 Jakarta</li>
        </ol>
        <h3>Media Sosial</h3>
        <ul>
            <li>Line id : daffayudhis89</li>
            <li>Nomor Hp : 085772746486</li>
            <li>Alamat E-mail : daffayudhistira27@gmail.com</li>
        </ul>
    </div>
{% endblock content %}
</html>

webs5/templates/Story3_aboutme.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html>
    {% block meta %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% endblock meta %}

    {% block content %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Fafdax</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'webs5:home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'webs5:eduskill' %}">Educations and skills</a>
                <a class="nav-item nav-link" href="{% url 'webs5:contact' %}">Contacts</a>
                <a class="nav-item nav-link" href="{% url 'webs5:Story1' %}">Story 1</a>
                <a class="nav-item nav-link" href="{% url 'webs5:s5matkul' %}">Story 5</a>
              </div>
            </div>
        </nav>
        <img src="{% static 'img/Foto profil.jpg' %}" alt="My photo" width="400" height="350" style="vertical-align:middle;margin:40px 480px">
        <div class="bio">
            <p>Nama lengkap: Muhammad Daffa Yudhistira Dwipayana</p>
            <p>NPM : 1906353441</p>
            <p>Umur : 19 tahun</p>
            <p>Angkatan : 2019</p>
            <p>Hobi : Bermain game dan membaca komik</p>
            <p>Tempat kuliah : Universitas Indonesia</p>
        </div>
        <br>
        <div class="desc">
            <h3>Deskripsi diri</h3>
            <p>Jika saya harus mendeskripsikan diri saya, saya orangnya itu baik dan ramah terhadap orang lain.<br>
            Sifat buruk saya diantaranya adalah agak pemalas jika mengerjakan sesuatu yang sulit.<br>Namun,
            jika saya menemukan suatu hal yang saya suka dan bisa saya kerjakan,<br> saya akan bersungguh-sungguh 
            dalam mengerjakan hal tersebut.
            </p>   
        </div>
    {% endblock content %}
</html>

webs5/templates/Story3_contact.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html>
    {% block meta %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% endblock meta %}

    {% block content %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Fafdax</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'webs5:aboutme' %}">About me</a>
                <a class="nav-item nav-link" href="{% url 'webs5:eduskill' %}">Educations and skills</a>
                <a class="nav-item nav-link" href="{% url 'webs5:home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'webs5:Story1' %}">Story 1</a>
                <a class="nav-item nav-link" href="{% url 'webs5:s5matkul' %}">Story 5</a>
              </div>
            </div>
        </nav>
        
        <div class="contacts">
            <h2>You can contact me here:</h2>
            <br>
            <img src="{% static 'img/line logo.png' %}" class="rounded mx-auto d-block" alt="Line" width="50" height="50">
            <h3>Line: daffayudhis89</h3>
            <br>
            <img src="{% static 'img/email logo.jpg' %}" class="rounded mx-auto d-block" alt="E-mail" width="50" height="50">
            <h3>Email: daffayudhistira27@gmail.com</h3>
            <br>
            <img src="{% static 'img/phone logo.png' %}" class="rounded mx-auto d-block" alt="Phone" width="50" height="50">
            <h3>Phone: 085772746486</h3>
        </div>
    {% endblock content %}
</html>

webs5/templates/Story3_eduskill.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html>
    {% block meta %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> 
        <style>
          h2{
            text-align: center;
            color: white;
          }
        </style>   
    {% endblock meta %}
     
    {% block content %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Fafdax</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'webs5:aboutme' %}">About me</a>
                <a class="nav-item nav-link" href="{% url 'webs5:home' %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'webs5:contact' %}">Contacts</a>
                <a class="nav-item nav-link" href="{% url 'webs5:Story1' %}">Story 1</a>
                <a class="nav-item nav-link" href="{% url 'webs5:s5matkul' %}">Story 5</a>
              </div>
            </div>
        </nav>
        <br>
        <h2>Here's some brief history about my educations:</h2>
        <div class="education">
            <p><b>SDI PB Soedirman</b></p> 
            <img src="{% static 'img/SDI PB Soedirman.jpg' %}" class="rounded mx-auto d-block" alt="SDI PB Soedirman" width="150" height="150">
            <br>
            <p><b>SMP Negeri 103 Jakarta</b></p> 
            <img src="{% static 'img/SMPN 103.png' %}" class="rounded mx-auto d-block" alt="SMP Negeri 103 Jakarta" width="150" height="150">
            <br>
            <p><b>SMA Negeri 98 Jakarta</b></p>
            <img src="{% static 'img/SMAN 98.jpg' %}" class="rounded mx-auto d-block" alt="SMA Negeri 98 Jakarta" width="150" height="150">
        </div>
        <br>
        <h2>And here's what I'm good at (currently)</h2>
        <div class="skills">
            <p><b>Python</b></p>
            <img src="{% static 'img/Python image.png' %}" class="rounded mx-auto d-block" alt="Python" width="150" height="150">
            <br>
            <p><b>Java</b></p>
            <img src="{% static 'img/Java image.png' %}" class="rounded mx-auto d-block" alt="Java" width="150" height="150">
            <br>
            <p><b>HTML</b></p>
            <img src="{% static 'img/HTML image.png' %}" class="rounded mx-auto d-block" alt="HTML" width="150" height="150">
        </div>
    {% endblock content %}
</html>

webs5/templates/Story5_detailMatkul.html
{% extends 'base2.html' %}
{% block content %}
<div class="card text-dark bg-white mt-2 mb-2 mx-auto" style="max-width: 60rem;">
    <div class="card-header d-flex justify-content-between">
      <div class="d-flex flex-column">
        <h5 class="my-auto">{{matkul.nama_matkul}}</h5>
        <p class="card-text m-1 mt-2">Ruangan: {{matkul.ruangan}}</p>
        <p class="card-text m-1">Dosen Pembawa: {{matkul.nama_dsn}}</p>
      </div>
      <div class="d-flex flex-column">
        <p class="mx-1">{{matkul.semester}}</p>
        <p class="mx-1">{{matkul.sks}} SKS</p>
      </div>
    </div>
    <div class="card-body">
      <p> {{matkul.deskripsi}} </p>
    </div>
  </div>
{% endblock %}

webs5/templates/Story5_matkul.html
{% extends 'base2.html' %}
{% block content %}
{% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
        {% endfor %}
{% endif %}

{% for matkul in lessons %}
<div class="card text-dark bg-white mt-2 mb-2 mx-auto" style="max-width: 60rem;">
    <div class="card-header d-flex justify-content-between">
      <h5 class="my-auto"> {{matkul.nama_matkul}} </h5>
      <div class="d-flex flex-row">
        <a href={{matkul.get_absolute_url}} class="btn btn-primary mx-1 my-auto">Detail</a>
        <form action="{% url 'webs5:delete' matkul.id %}" class="my-auto"method="POST">
         {% csrf_token %}
         <button class="btn btn-primary mx-1" type="input">Delete</button>
        </form>
      </div>
    </div>
    <div class="card-body">
      <p class="card-text m-1">Ruangan: {{matkul.ruangan}} </p>
      <p class="card-text m-1">Dosen Pembawa: {{matkul.nama_dsn}} </p>
    </div>
</div>
{% endfor %}
{% endblock %}

webs5/templates/Story5_tambahMatkul.html
{% extends 'base2.html' %}
{% block content %}
<form method = "POST" action = "{% url 'webs5:s5tm' %}">
{% csrf_token %}
    <div class="card text-dark bg-white mt-1 mb-3 mx-auto" style="max-width: 60rem;">
        <div class="card-header d-flex justify-content-between">
            <div class="d-flex flex-column">
                <h5 class="my-auto"><input class="form-control-lg col-9 mb-3 p-0" placeholder="Nama matkul" name="nama_matkul" required></h5>
                <p class="card-text m-1 mt-2">Ruangan: <input class="form-control-sm w-75 ml-1" placeholder="Kode Ruangan" name="ruangan" required></p>
                <p class="card-text m-1">Nama Dosen: <input class="form-control-sm w-75 ml-1" placeholder="Nama dosen" name="nama_dsn" required></p>
            </div>
            <div class="d-flex flex-column">
                <p class="mx-1">Semester:<select class="form-control mb-1" name="semester" required>
                          <option value="2019/2020 Gasal">2019/2020 Gasal</option>
                          <option value="2019/2020 Genap">2019/2020 Genap</option>
                          <option value="2020/2021 Gasal">2020/2021 Gasal</option>
                          <option value="2020/2021 Genap">2020/2021 Genap</option>
                          <option value="2021/2022 Gasal">2021/2022 Gasal</option>
                          <option value="2021/2022 Genap">2021/2022 Genap</option>
                          <option value="2022/2023 Gasal">2022/2023 Gasal</option>
                          <option value="2022/2023 Genap">2022/2023 Genap</option>
                        </select></p>
                <p class="mx-1">SKS: <input class="form-control" type="number" value=1 name="sks" required></p>
                <button class="btn btn-primary" type="submit">Tambah Matkul</button>
            </div>
        </div>
        <div class="card-body">
            <p> <textarea class="form-control w-100" placeholder="Deskripsi mata kuliah" name="deskripsi" required></textarea></p>
        </div>
    </div>  
</form>
{% endblock %}

webs5/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
</body>
  {% block content %}
  {% endblock content %}
</html>

webs5/templates/base2.html
{% load static %}
<html lang=en>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>

    <body style="background-color: gold;">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">My Matkul</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'webs5:s5matkul' %}">Matkul</a>
                <a class="nav-item nav-link" href="{% url 'webs5:s5tm' %}">Tambah Matkul</a>
                <a class="nav-item nav-link" href="{% url 'webs5:Story1' %}">Story 1</a>
                <a class="nav-item nav-link" href="{% url 'webs5:home' %}">Story 3</a>
              </div>
            </div>
        </nav>
          
        {% block content %}
        {% endblock %}
    </body>
</html>

webs5/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html>
    {% block meta %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <style>
            div{
                text-align: center;
                font-size: 24;
                color: white;
            }
            h1{
                color: white;
                text-align: center;
            }
        </style>
    {% endblock meta %}

    {% block content %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Fafdax</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'webs5:aboutme' %}">About me</a>
                <a class="nav-item nav-link" href="{% url 'webs5:eduskill' %}">Educations and skills</a>
                <a class="nav-item nav-link" href="{% url 'webs5:contact' %}">Contacts</a>
                <a class="nav-item nav-link" href="{% url 'webs5:Story1' %}">Story 1</a>
                <a class="nav-item nav-link" href="{% url 'webs5:s5matkul' %}">Story 5</a>
              </div>
            </div>
          </nav>
    <img src="{% static 'img/Foto profil.jpg' %}" alt="My photo" width="400" height="350" style="vertical-align:middle;margin:40px 500px">
    <h1><i>Hello, my name is Daffa</i></h1>
    <div><b>I'm a newbie programmer and web developer</b><br><b>Nice to meet you!</b></div>
    {% endblock content %}
</html>